- hosts: terraform-ansible
  tasks: 
  - name: Instalando pyhton
    apt:
       pkg:
       - python3
       - virtualenv
       update_cache: yes
    become: yes
  - name: Git clone
    ansible.builtin.git:
      repo: https://github.com/guilhermeonrails/clientes-leo-api.git
      dest: /home/ubuntu/estudo
      version: master
      #Force irá forçar que o clone do git sobreponha as modificações / vai sempre pegar a versão mais nova do código
      force: yes
  - name: Instalando dependencias com pip
    pip:
      virtualenv: /home/ubuntu/estudo/venv
      #Requirements vai verificar o caminho e instalar as dependencias necessárias
      requirements: /home/ubuntu/estudo/requirements.txt
  - name: Alterando hosts do settings
    lineinfile:
      path: /home/ubuntu/estudo/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: Configurando o banco de dados
    shell: '. /home/ubuntu/estudo/venv/bin/activate; python /home/ubuntu/estudo/manage.py migrate'
  - name: Carregando dados iniciais
    shell: '. /home/ubuntu/estudo/venv/bin/activate; python /home/ubuntu/estudo/manage.py loaddata clientes.json'
  - name: Iniciando o servidor
    shell: '. /home/ubuntu/estudo/venv/bin/activate; nohup python /home/ubuntu/estudo/manage.py runserver 0.0.0.0:8000 &'
