- hosts: terraform-ansible
  tasks: 
  - name: Instalando pyhton
    apt:
       pkg:
       - python3
       - virtualenv
       update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Djando e Djandorest)
    pip:
      virtualenv: /home/ubuntu/estudo/venv
      name:
      - django
      - djangorestframework
  - name: Verificando se o projeto ja existe
    stat:
      path: /home/ubuntu/estudo/setup/settings.py
    register: projeto
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/estudo/venv/bin/activate; django-admin startproject setup /home/ubuntu/estudo'
    when: not projeto.stat.exists
    #Esse parâmetro vai fazer com que o playbook continue independente do comando ter retornado OK, changed ou fail.
    #ignore_errors: yes
  - name: Alterando hosts do settings
    lineinfile:
      path: /home/ubuntu/estudo/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
